seer_ukd_wright_gallery_homepage:
    pattern:  /gallery/
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:galleryHome }
    requirements:
        _method: GET

seer_ukd_wright_gallery_gallery_short:
    pattern:  /gallery/{galleryId}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:gallery }
    requirements:
        _method: GET
        galleryId: \d+