seer_ukd_wright_gallery_homepage:
    pattern:  /gallery
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:index }

seer_ukd_wright_gallery_gallery_short:
    pattern:  /gallery/{galleryId}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:gallery }

seer_ukd_wright_gallery_gallery:
    pattern:  /gallery/{galleryId}-{slug}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:gallery }

seer_ukd_wright_gallery_category_short:
    pattern:  /gallery/category/{categoryId}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:galleryCategory }

seer_ukd_wright_gallery_category:
    pattern:  /gallery/category/{categoryId}-{slug}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:galleryCategory }