seer_ukd_wright_gallery_homepage:
    pattern:  /gallery
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:index }

seer_ukd_wright_gallery_gallery_short:
    pattern:  /gallery/{galleryId}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:gallery }
    requirements:
        _method: GET
        galleryId: \d+

seer_ukd_wright_gallery_category_short:
    pattern:  /gallery/category/{categoryId}
    defaults: { _controller: SeerUKDWrightGalleryBundle:Gallery:galleryCategory }
    requirements:
        _method: GET
        categoryId: \d+