parameters:
    seer_ukd_wright_gallery.gallery_helper.class: SeerUK\DWright\GalleryBundle\Helper\GalleryHelper
    seer_ukd_wright_gallery.create_gallery_model.class: SeerUK\DWright\GalleryBundle\Form\Model\CreateGallery;

services:
    seer_ukd_wright_gallery.gallery_helper:
        class: %seer_ukd_wright_gallery.gallery_helper.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
