parameters:
#    seer_ukd_wright_security.example.class: SeerUK\DWright\SecurityBundle\Example

services:
#    seer_ukd_wright_security.example:
#        class: %seer_ukd_wright_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
