primary:
    Home:
        enabled: true

    About:
        enabled: true

    Portfolio:
        enabled: true
        routes:
            - "seer_ukd_wright_gallery_homepage"
            - "seer_ukd_wright_gallery_gallery_short"
        target: "seer_ukd_wright_gallery_homepage"

    Contact:
        enabled: true

admin_primary:
    Home:
        enabled: true
        class: flaticon stroke home-2

    About:
        enabled: true
        class: flaticon stroke article-3

    Portfolio:
        enabled: true
        class: flaticon stroke photo-1
        routes:
            - "seer_ukd_wright_admin_gallery"
            - "seer_ukd_wright_admin_gallery_new_gallery"
        target: "seer_ukd_wright_admin_gallery"

    Contact:
        enabled: true
        class: flaticon stroke mail-3

    spacer2:
        enabled: true
        class: spacer

    Settings:
        enabled: true
        class: flaticon stroke settings-1