primary:
    Home:
        enabled: true

    About:
        enabled: true

    Portfolio:
        enabled: true
        routes:
            - "seer_ukd_wright_gallery_homepage"
            - "seer_ukd_wright_gallery_gallery_short"
        target: "seer_ukd_wright_gallery_homepage"

    Contact:
        enabled: true

admin_primary:
    Dashboard:
        enabled: true
        class: graph-2

    Pages:
        enabled: true
        class: article-3

    Portfolio:
        enabled: true
        class: camera-4
        routes:
            - "seer_ukd_wright_admin_gallery"
            - "seer_ukd_wright_admin_gallery_new"
        target: "seer_ukd_wright_admin_gallery"

    Settings:
        enabled: true
        class: settings-1