primary:
    Home:
        enabled: true

    About:
        enabled: true

    Portfolio:
        enabled: true
        routes:
            - "seer_ukd_wright_gallery_homepage"
            - "seer_ukd_wright_gallery_gallery_short"
        target: "seer_ukd_wright_gallery_homepage"

    Contact:
        enabled: true
