primary:
    Home:
        enabled: true

    About:
        enabled: true

    Portfolio:
        enabled: true
        routes:
            - "seer_ukd_wright_gallery_homepage"
            - "seer_ukd_wright_gallery_gallery_short"
        target: "seer_ukd_wright_gallery_homepage"

    Contact:
        enabled: true

admin_primary:
    Dashboard:
        enabled: true
        class: flaticon stroke graph-2

    Pages:
        enabled: true
        class: flaticon stroke article-3

    Portfolio:
        enabled: true
        class: flaticon stroke photo-1
        routes:
            - "seer_ukd_wright_admin_gallery"
            - "seer_ukd_wright_admin_gallery_new"
        target: "seer_ukd_wright_admin_gallery"

    Settings:
        enabled: true
        class: flaticon stroke settings-1