primary:
    Home:
        enabled: true

    About:
        enabled: true

    Portfolio:
        enabled: true
        routes:
            - "seer_ukd_wright_gallery_homepage"
            - "seer_ukd_wright_gallery_gallery_short"
        target: "seer_ukd_wright_gallery_homepage"

    Contact:
        enabled: true

admin_primary:
    Home:
        enabled: true
        class: nav-icon-dashboard

    spacer1:
        enabled: true
        class: spacer

    About:
        enabled: true
        class: nav-icon-page

    Portfolio:
        enabled: true
        class: nav-icon-gallery
        routes:
            - "seer_ukd_wright_admin_gallery"
        target: "seer_ukd_wright_admin_gallery"

    Contact:
        enabled: true
        class: nav-icon-page

    spacer2:
        enabled: true
        class: spacer

    Settings:
        enabled: true
        class: nav-icon-grid