parameters:
#    seer_ukd_wright_core.example.class: SeerUK\DWright\CoreBundle\Example

services:
#    seer_ukd_wright_core.example:
#        class: %seer_ukd_wright_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
