parameters:
    # Date Time Formatter
    seer_ukd_wright_core.date_time_formatter.class: SeerUK\DWright\CoreBundle\Helpers\DateTime\DateTimeFormatter
    seer_ukd_wright_core.twig.date_time_formatter.class: SeerUK\DWright\CoreBundle\Twig\DateTimeFormatterExtension

services:
    # Date Time Formatter
    seer_ukd_wright_core.date_time_formatter:
        class: %seer_ukd_wright_core.date_time_formatter.class%

    seer_ukd_wright_core.twig.date_time_formatter:
        class: %seer_ukd_wright_core.twig.date_time_formatter.class%
        arguments: [@seer_ukd_wright_core.date_time_formatter]
        tags:
            - { name: twig.extension }
