parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: dwright
    database_user: root
    database_password: Diablo2
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 2872f2f668f43009c6f71fd478d0ccd5
    database_path: null
    site_name: David Wright Images
