seer_ukd_wright_core:
    resource: "@SeerUKDWrightCoreBundle/Resources/config/routing.yml"
    prefix:   /

seer_ukd_wright_gallery:
    resource: "@SeerUKDWrightGalleryBundle/Resources/config/routing.yml"
    prefix:   /

