jms_security_extra:
    secure_all_services: false
    expressions:         true

security:
    encoders:
        SeerUK\DWright\SecurityBundle\Entity\User:
            algorithm: bcrypt
            cost:      15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default:
            entity: { class: SeerUKDWrightSecurityBundle:User, property: userName }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/account/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /account/login/check
                login_path: /account/login
            logout:
                path:   /account/logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/account/login, access: isAnonymous() }
        - { path: ^/admin, roles: ROLE_ADMIN }
